### PR TITLE
Updated Avalonia to 0.10.0-preview1

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Updated Avalonia to 0.10.0-preview1:
  - Updated default text color and font size:
    - Text color is now based on fluent theme resources (won't work for default theme, which I think will be deprecated soon anyway).
    - Font size is now constant `14.0f` (this value comes from fluent theme resources, there is also a bug which blocks using the resource: it is `double`, but font size is `float`, probably a bug in Avalonia).
  - Updated Avalonia sample:
    - Also removed `SideBar.xaml`: the default styles for `TabControl` is good in fluent theme, also the side bar styles don't look good in fluent.

### CODE REVIEW

**Comment by Happypig375** [comment]
>Font size is now constant 14.0f (this value comes from fluent theme resources, there is also a bug which blocks using the resource: it is double, but font size is float, probably a bug in Avalonia).

As noted in https://github.com/verybadcat/CSharpMath/pull/121#issuecomment-647039155, this is also a problem for Platform Uno. The solution would be to change all `float` properties to `double`, but that change will be done in #121. 

Also this value (14) would be great as the default across all platforms. The current default, 50, is definitely too large. I'll add a commit that implements this change.

**Comment by FoggyFinder** [comment]
I got `System.InvalidOperationException: "The control already has a visual parent."` while switching between themes.
Let's check whether it is an Avalonia bug or something on our side before merge

**Comment by Happypig375** [comment]
I think this is https://github.com/AvaloniaUI/Avalonia/issues/4265.

**Comment by FoggyFinder** [comment]
To avoid crash I think it would be better to replace `ComboBox` here with `ToggleSwitch` or something like that

**Comment by FoggyFinder** [comment]
I tried to use `ToggleSwitch` but all my attempts are failed. Despite themes are replaced the toggle itself was remain on the same position. Unclear why.

Two `RadioButton` seems safest option :-)

I can do it in the evening if better solution won't be found.

**Comment by Happypig375** [comment]
Can the `RadioButton` text be vertically centered relative to the circles?
image

**Pull request merged**
