### PR TITLE
Added Avalonia implementation

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Added Avalonia implementation.
- Added Avalonia example.

Also had to add NuGet.config with the Avalonia nightly feed, as there were some breaking changes since 0.7.0 and it's easier to maintain if we always use latest nightly version.

Custom fonts are not supported yet (left 2 methods in `MathBlock` and `TextBlock` to update font, but it's not implemented).

### CODE REVIEW

**Comment by charlesroddie** [comment]
How does this approach compare to just referencing CSharpMath.SkiaSharp?

**Comment by jp2masa** [comment]
You don't have to use SkiaSharp, it will work on any backend.

**Comment by charlesroddie** [comment]
Are there Avalonia platforms ("backends"?) on which SkiaSharp doesn't work?

**Comment by jp2masa** [comment]
I don't think so. I think the only backends are SkiaSharp and Direct2D, so SkiaSharp covers all platforms.

**Comment by Happypig375** [comment]
I'll review maybe a few days later. Don't have much time now.

**Comment by charlesroddie** [comment]
@jp2masa do you want to maintain CSharpMath.Avalonia?

Lowest maintenance: example projects using CSharpMath.SkiaSharp directly.
Medium maintenance: an Avalonia wrapper around CSharpMath.SkiaSharp.
High maintenance: new Avalonia renderer. You would probably need to maintain this and manage the nuget release in this case.

**Comment by Happypig375** [comment]
@jp2masa Do you know of how to get an Avalonia FontFamily's raw bytes (probably as a Stream)? That would be needed for a custom font for CSharpMath.

**Comment by jp2masa** [comment]
@charlesroddie I have no problem in maintaining `CSharpMath.Avalonia`, but I thought you would be interested in having an Avalonia renderer. I could as well just create a repo for this then.

@Happypig375 I tried to keep things simple, I'll try implementing fonts when I have time, probably not really hard.

**Comment by Happypig375** [comment]
@jp2masa Thanks for spending your free time here. I'll review the sample today. If you want to become a Collaborator to be able to push commits to this repo directly, just ask. I'll contact @verybadcat.

**Comment by charlesroddie** [comment]
> I thought you would be interested in having an Avalonia renderer

I'm uncertain about this given that we already have Avalonia support via CSharpMath.SkiaSharp. I think we should only merge this if there is better for Avalonia users to have CSM.Avalonia implemented via a Avalonia renderer (3) vs using CSM.SkiaSharp directly (1) or via a wrapper (2). Can you think of any advantages?

We do have multiple approaches for iOS (CSM.SkiaSharp/CSM.Forms, CSM.iOS) but this is more of a historical artifact given that CSM.iOS came first. A Xamarin.iOS user would actually be better off using CSM.SkiaSharp (for flexibility and stability) or CSM.Forms (for something very easy with extra convenience features).

**Comment by jp2masa** [comment]
I believe forcing the use of SkiaSharp is not really good, although it would work in most cases I think. Also not sure about deferred rendering in Avalonia, before implementing the custom renderer I used `CSharpMath.SkiaSharp` and I had to use immediate rendering to get the `SKCanvas` easily, not sure if there's some way of creating an `SKCanvas` for deferred rendering.

**Comment by charlesroddie** [comment]
> @jp2masa I believe forcing the use of SkiaSharp is not really good

Because of deferred rendering?

> not sure if there's some way of creating an `SKCanvas` for deferred rendering.

If the question is rendering of CSharpMath objects, then MathPainter and TextPainter are in some sense deferred rendering, and can be brought closer to the render if needed.

More generally with SkiaSharp, rendering independent of a View is not currently in the main repo but can be added: https://github.com/mono/SkiaSharp/issues/688

**Comment by Happypig375** [comment]
@jp2masa Can you finish the font part?

**Comment by jp2masa** [comment]
I'll work on this.

**Comment by Happypig375** [comment]
Cleaning up stale PRs, merging

**Comment by Happypig375** [comment]
For some reason, GitHub didn't register the commits

**Comment by jp2masa** [comment]
@Happypig375 It looks like only the first commit was merged. The second commit has some important changes I believe. Just asking if that was the intention?

**Comment by Happypig375** [comment]
Interesting.

**Comment by Happypig375** [comment]
@jp2masa The rendered output in Avalonia seems bolded. It is a bit hard to read. The fraction lines are too thin as well. Do you have any ideas on how to solve this? Ideally the rendered output should be identical to using the SkiaSharp front end.

**Comment by Happypig375** [comment]
image

**Comment by Happypig375** [comment]
Same font size: 12 on Forms.Example

image

**Comment by jp2masa** [comment]
I'll take a look.

**Comment by Happypig375** [comment]
Ideally all tests in CSharpMath.Rendering Tests should pass.

**Comment by jp2masa** [comment]
A quick hack is setting the pen thickness to `0.001` in this line:

https://github.com/verybadcat/CSharpMath/blob/58f860862f91a8b4a5c81c0b2989b0b87cb9ff30/CSharpMath.Avalonia/AvaloniaPath.cs#L45

```cs
new Pen(brush, 0.001)
```

I don't know why, maybe it's an Avalonia issue.

**Comment by Happypig375** [comment]
@jp2masa Seems that AvaloniaProperties behave a little differently than Xamarin.Forms BindableProperties that is causing a test in CSharpMath.Xaml.Tests to fail. While debugging, I noticed that Avalonia assigned an old value to a Property when `PropertyChanged` is raised after setting the new value. Can you take a look?

**Comment by jp2masa** [comment]
I'll take a look.

**Comment by jp2masa** [comment]
The problem is the previous `OneWayToSource` binding. Forms processes the latest bindings first (I tested it), Avalonia processes them in the order they were created.

**Pull request merged**
