### PR TITLE
Ported into net standard 2.0

### PR DESCRIPTION
**Pull request by hflexgrig**

### CODE REVIEW

**Comment by Happypig375** [comment]
Note to consider: This removes support for older platforms, e.g. UWP pre-Fall Creators Update.

**Comment by Happypig375** [comment]
@charlesroddie Is this acceptable?

**Comment by hflexgrig** [comment]
Maybe we can keep another dedicated branch for netstandard 2.0 ?

**Comment by charlesroddie** [comment]
> @charlesroddie Is this acceptable?

netstandard2.0 makes sense as hygiene.

This PR isn't complete. There are some references to things that can't be done in netstandard1.3 (analyzers) that can be removed/fixed, and bound to be some other things that are enabled by netstandard2.0.

> Maybe we can keep another dedicated branch for netstandard 2.0 ?

Too complex and the main benefit of this PR will be simplification.

**Comment by Happypig375** [comment]
The analyzer doesn't do much yet to be useful by itself, but serves as a future extension point. Merging.

**Pull request merged**
