### PR TITLE
Update MathPainter.cs

### PR DESCRIPTION
**Pull request by sadqiang**
Refactoring DrawDisplay.

### CODE REVIEW

**Comment by Happypig375** [comment]
Thanks!

**Comment by sadqiang** [comment]
Sorry, as I am not familiar with github and git as well,  is it ok if  I delete `sadqiang:patch-1` branch now?

**Comment by FoggyFinder** [comment]
absolutely

**Comment by Happypig375** [comment]
Because the changes are now implemented, you don't have to keep the branch anymore.

**Pull request merged**
