### PR TITLE
Change AngouriMath reference to use NuGet package instead of git submodule

### PR DESCRIPTION
**Pull request by Happypig375**
Also added a calculator to Avalonia Example

### CODE REVIEW

**Comment by FoggyFinder** [comment]
Maybe it makes sense to update to latest Avalonia here as well?

**Comment by Happypig375** [comment]
@FoggyFinder @jp2masa Avalonia 0.10.0-preview2 removed `Avalonia.Markup.Xaml.AvaloniaXamlLoader.Parse<T>(string)`. Is there a replacement?

**Comment by Happypig375** [comment]
Okay, found the commit that removed this: https://github.com/AvaloniaUI/Avalonia/commit/d355007c57a71184e56f2d92d49cf83c05401413

**Comment by FoggyFinder** [comment]
> Avalonia 0.10.0-preview2 removed Avalonia.Markup.Xaml.AvaloniaXamlLoader.Parse<T>(string). Is there a replacement?

It is moved into the separate package:

[Avalonia.Markup.Xaml.Loader](https://www.nuget.org/packages/Avalonia.Markup.Xaml.Loader/0.10.0-preview2)

**Pull request merged**
