### PR TITLE
Add mathkeyboard test using random inputs

### PR DESCRIPTION
**Pull request by charlesroddie**
Adds 100 random keypresses to a MathKeyboard and gets LaTeX and checks that there is no crash

### CODE REVIEW

**Comment by FoggyFinder** [comment]
Why add another test project?
Also, why use `nunit` instead of `xUnit`?

**Comment by charlesroddie** [comment]
So I can use F#. You are welcome to change from nunit to xUnit if you'd like.

**Comment by charlesroddie** [comment]
```
System.Exception : Exeption: Object reference not set to an instance of an object. inputs: [A; Sine; LeftRoundBracket; LeftRoundBracket; BothRoundBrackets]
```

**Comment by charlesroddie** [comment]
```
System.Exception : Exeption: Object reference not set to an instance of an object. inputs: [Power; Up; Left; B; B; Power]
```

**Comment by FoggyFinder** [comment]
Yep, it is: #78. I used subscript for description there but the problem is exactly the same.

**Comment by charlesroddie** [comment]
It gets the shortest error case and tends to find `[Power; Left; Power]` now, again the same error.

**Pull request merged**
